---
title: "Amer.Option"
author: "Jed DeCamp"
date: "May 5, 2017"
output: html_document
---

American Option:

import numpy as np

class VanillaOption(object):
    def __init__(self, strike, expiry, payoff):
        self.__strike = strike
        self.__expiry = expiry
        self.__payoff = payoff
        
    @property
    def strike(self):
        return self.__strike
    
    @property
    def expiry(self):
        return self.__expiry
    
    def payoff(self, spot):
        return self.__payoff(self, spot)
        
def call_payoff(option, spot):
    return np.maximum(spot - option.strike, 0.0)

def put_payoff(option, spot):
    return np.maximum(option.strike - spot, 0.0)
    
def AmericanBinomial(option, spot, rate, volatility, dividend, steps):
    return np.maximum()
    
spot = 41
strike = 40.0
expiry = 1.0
rate = 0.08
volatility = 0.3
dividend = 0.0
steps = 3
num_nodes = steps + 1

dt = expiry / steps
u = np.exp((rate * dt) + volatility * np.sqrt(dt))
d = np.exp((rate * dt) - volatility * np.sqrt(dt))
pu = (np.exp(rate * dt) - d) / (u - d)
pd = 1 - pu
disc = np.exp(-rate * dt)
dpu = disc * pu
dpd = disc * pd
    
cashFlow_t = np.zeros((num_nodes, ))
spot_t = np.zeros((num_nodes, ))
option = VanillaOption(strike, expiry, put_payoff)
    
for i in range(num_nodes):
    spot_t[i] = spot * (u ** (steps - i)) * (d ** i)
    cashFlow_t[i] = option.payoff(spot_t[i]) 

for i in range((steps - 1), -1, -1):
    for j in range(i+1):
        cashFlow_t[j] = dpu * cashFlow_t[j] + dpd * cashFlow_t[j+1]
        spot_t[j] = spot_t[j] / u
        cashFlow_t[j] = np.maximum(cashFlow_t[j], option.payoff(spot_t[j]))    
    
price = cashFlow_t[0]
    
print ("The Option Price is: {0:.4f}".format(price))